# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa2c8d7f07fa077fc833cb1c8ae478d4f3d45c22b3c246aea81941fd69cd2ae8d821e37398c77041bc922ffbe0e8aa9a479336a04e4a8816993542ffb5fce5d

test:
  secret_key_base: 93d930d67e33a9e83f61856e97b0139e96ff3e5824ddcc3a8de3e03a3ac4432b8833687985fda160ee5893da90dd81e3d5a6d8d98a3ec525b57f48690767649e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
